### ISSUE TITLE
VM not available anymore

### ISSUE THREAD

**Issue by rogererens** [jcfr/scipy2014_boost_python_workshop_student_material#1]
I'd like to follow along the Integrating Python and C++ with Boost workshop from SciPy2014.
Unfortunately,
https://www.dropbox.com/s/vs4oh9lsaiogtfy/BoostPythonWorkshop.ova
gives a 404. Can you make the VM available again (not necessarily in the same location)?

I'm on MacOSX 10.11.3, and with CMake3.4.3 and python2.7.11 the instructions for setting up a Mac OL X system using CMake or ordinary make fail as well, which is why I turned to look at the VM.

TIA!

**Comment by shibasisp** [comment]
Here you go! https://www.dropbox.com/s/g942rgtsjg4hkjd/BoostPythonWorkshop.ova?dl=0 I am trying to update the README.md.

**Comment by jcfr** [comment]
Thanks. 

Closing. Fixed in #2
